name: Deploy to GitHub Pages

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write 
      pages: write
      id-token: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Setup Bun
        uses: oven-sh/setup-bun@v2.0.2

      - name: Install dependencies
        run: bun install

      - name: Build static files
        env:
          BUN_PUBLIC_CLIENT_ID: "661847183866-i5nu2ummfd03viv1fnul0ctmhs5rrehk.apps.googleusercontent.com" 
          BUN_PUBLIC_API_KEY: "Jeje nose"
          BUN_PUBLIC_DISCOVERY_DOC: "https://www.googleapis.com/discovery/v1/apis/gmail/v1/rest"
          BUN_PUBLIC_SCOPES: "https://www.googleapis.com/auth/gmail.readonly https://www.googleapis.com/auth/gmail.send"
        run: |
          echo "--- Starting Bun Build ---"
          echo "Discovery Doc (para verificar): $BUN_PUBLIC_DISCOVERY_DOC"
          echo "Scopes (para verificar): $BUN_PUBLIC_SCOPES"
          bun run build
        
      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: './dist' 

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4