name: Deploy to GitHub Pages

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write 
      pages: write
      id-token: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Setup Bun
        uses: oven-sh/setup-bun@v2.0.2

      - name: Install dependencies
        run: bun install

      - name: Build static files
        env:
          BUN_PUBLIC_CLIENT_ID: ${{ secrets.BUN_PUBLIC_CLIENT_ID }} 
          BUN_PUBLIC_API_KEY: ${{ secrets.BUN_PUBLIC_API_KEY }} 
          BUN_PUBLIC_DISCOVERY_DOC: ${{ secrets.BUN_PUBLIC_DISCOVERY_DOC }} 
          BUN_PUBLIC_SCOPES: ${{ secrets.BUN_PUBLIC_SCOPES }} 
        run: |
          echo "--- Starting Bun Build ---"
          echo "Discovery Doc (para verificar): $BUN_PUBLIC_DISCOVERY_DOC"
          echo "Scopes (para verificar): $BUN_PUBLIC_SCOPES"
          bun run build
        
      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: './dist' 

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4